import Feature from 'ol/Feature.js';
import Point from 'ol/geom/Point.js';
import { fromLonLat } from 'ol/proj.js';
import Icon from 'ol/style/Icon.js';
import Style from 'ol/style/Style.js';
import lynnHallSidebar from "./assets/images/lynnhallsidebar.jpg";
import cfaSidebar from "./assets/images/cfaSidebar.jpg";
import classicHallSidebar from "./assets/images/classicHallSidebar.jpg";
import greenwoodSidebar from "./assets/images/greenwoodSidebar.jpg";
import dugganLibrarySidebar from "./assets/images/librarySidebar.jpg";
import scienceCenterSidebar from "./assets/images/scienceCenterSidebar.jpg";
import coulterSidebar from "./assets/images/coulterSidebar.jpg";
import blytheSidebar from "./assets/images/blytheSidebar.jpg";
import donnerSidebar from "./assets/images/donnerSidebar.jpg";
import croweSidebar from "./assets/images/croweSidebar.jpg";
import wileySidebar from "./assets/images/wileySidebar.jpg";
import ideSidebar from "./assets/images/ideSidebar.jpg";
import kpSidebar from "./assets/images/kpSidebar.jpg";
import ogleSidebar from "./assets/images/ogleSidebar.jpg";
import baseballSidebar from "./assets/images/baseballSidebar.jpg";
import softballSidebar from "./assets/images/softballSidebar.jpg";
import hornerSidebar from "./assets/images/hornerSidebar.jpg";
import arenaSidebar from "./assets/images/arenaSidebar.png";
import stadiumSidebar from "./assets/images/stadiumSidebar.png";
import soccerSidebar from "./assets/images/soccerSidebar.png";
import tennisSidebar from "./assets/images/tennisSidebar.png";
import phiDeltaThetaSidebar from "./assets/images/phideltSidebar.jpg";
import sigmachiSidebar from "./assets/images/sigmachiSidebar.jpg";
import fijiSidebar from "./assets/images/fijiSidebar.jpg"
import chioSidebar from "./assets/images/chioSidebar.jpg";
import adpiSidebar from "./assets/images/adpiSidebar.jpg";
import phimuSidebar from "./assets/images/phimuSidebar.png";
import thetaSidebar from "./assets/images/thetaSidebar.jpg";
import shoeboxSidebar from "./assets/images/shoeboxSidebar.jpg";
import ugSidebar from "./assets/images/ugSidebar.jpg";
import ccSidebar from "./assets/images/ccSidebar.jpg";
import pointSidebar from "./assets/images/pointSidebar.jpg";
import observatory from "./assets/images/culbertsonObservatory.jpg";
import {coords} from './coords';

// Function to create a feature with a specified name, coordinates, and info
const createFeature = (name, type, coords, scheduleLink, imageUrl, info) => {
  const feature = new Feature({
    geometry: new Point(fromLonLat(coords)),
    name: name,
    type: type,
    scheduleLink: scheduleLink,
    imageUrl: imageUrl,
    info: info,
  });

  return feature;
};

// athletic links and features
const soccerLinks = ['https://athletics.hanover.edu/sports/mens-soccer/schedule/2024', 'https://athletics.hanover.edu/sports/womens-soccer/schedule']
const tennisLinks = ['https://athletics.hanover.edu/sports/mens-tennis/schedule/2023-24', "https://athletics.hanover.edu/sports/womens-tennis/schedule/2024-25"]
const stadiumLinks = ['https://athletics.hanover.edu/sports/football/schedule/2024', "https://athletics.hanover.edu/sports/mens-lacrosse/schedule/2024", "https://athletics.hanover.edu/sports/womens-lacrosse/schedule"]
const arenaLinks = ['https://athletics.hanover.edu/sports/mens-basketball/schedule/2024-25', 'https://athletics.hanover.edu/sports/womens-basketball/schedule/2024-25', 'https://athletics.hanover.edu/sports/womens-volleyball/schedule/2024']

export const stadiumFeature = createFeature("Alumni Stadium", "Athletics", coords.stadium, stadiumLinks, stadiumSidebar, "The 4,000-seat venue, with its all-weather artificial surface, is home to Hanover's football, men's and women's lacrosse and men's and women's track & field teams. The stadium is a part of Hanover's Outdoor Athletic Complex, which accommodates facilities for 15 of the College's outdoor sports. <br><br>The stadium features a three-level press box, which includes locker rooms, classrooms, athletic training offices and equipment and offices for the Panther football coaching staff. The College's golf team also has an indoor practice facility located on the first floor of the stadium.");
export const soccerFeature = createFeature("Soccer Fields", "Athletics", coords.soccer, soccerLinks, soccerSidebar, "The men's and women's soccer programs use two natural turf fields, including a practice and a game field, and also host occasional matches on Alumni Stadium's artificial surface. <br><br> The game field also features the Hagenah Press Box, sheltered benches for each team, a scoreboard at each end of the field, and seating down the far side.");
export const tennisFeature = createFeature("Zeddies Tennis Center", "Athletics", coords.tennis, tennisLinks, tennisSidebar, "Completed in 2012, the Zeddies Tennis Center, made possible by a gift from Michael ’77 and Judy Zeddies, features a total of eight courts.<br><br>In addition to the eight courts, Zeddies Tennis Center also consists of an adjacent lighted pavilion and storage space. <br><br> Part of the Panther Athletic Complex, Zeddies Tennis Center sits directly behind Alumni Stadium and is adjacent to grass practice fields that are available for the College’s outdoor teams and intramural sports.");
export const baseballFeature = createFeature("K.T. Young Ballpark", "Athletics", coords.baseball, 'https://athletics.hanover.edu/sports/baseball/schedule/2024', baseballSidebar,"Scenic K.T. Young Ballpark, home to the Panthers since 1972, is one of the nicest in the Midwest. The field saw recent improvements in 2014 when professional style dugouts and bullpens were added along with a press box, a new scoreboard, and two 70-foot batting cages down the left field line. It features a crushed red brick and natural turf infield and an outfield fence lined with more than 100 trees. The field also has a sprinkler system throughout the field.<br><br>The park is named after Kenneth T. Young '65 and in memory of Thomas D. Young '39 for their participation in and support of athletic programs at Hanover College.<br><br>The field is named Dick Naylor Field in honor of former head baseball coach Dick Naylor for his outstanding service to Hanover College and his accomplishments as head baseball coach for 36 years.<br><br>The Gaunt Grandstands and Press Box are named in honor of Jim '67 and Kate Gaunt for their special interest in the students of Hanover College and for their generous financial support to the athletic facilities project of the Live Our Loyalty Campaign. " )
export const softballFeature = createFeature("Kops-Bedel Stadium", "Athletics", coords.softball, 'https://athletics.hanover.edu/sports/softball', softballSidebar, "Hanover's softball team plays on one of the Midwest's finest fields. Kops-Bedel Stadium features a crushed red-brick infield and an agrilime warning track in the outfield along with professional style dugouts, bullpens for each side, batting cages, and a press box.<br><br>The stadium is named in honor of Elaine E. Kops-Bedel '74 and Eric J. Bedel in recognition of her special interest in the women students of Hanover College, her leadership in securing financial support for athletic facilities, and their generous contributions to the Live Our Loyalty Campaign.<br><br>The field is named Brouillette Field for Donald G. & Marilyn Brouillette by their daughter, JoAnn Brouillette '83 in honor of their inspiration and impact on family, community, Hanover College, and women's sports.<br><br>The Rector-Gleason Grandstands and Press Box are named in honor of Greg '72 and Kristine Rector Gleason '73 in recognition of their support of the Live Our Loyalty Campaign of Hanover College.");
export const hornerFeature = createFeature("Horner Center", "Athletics", coords.horner, '', hornerSidebar, "The Horner Health and Recreation Center supports the Hanover community’s pursuit of recreational and intercollegiate sports, physical fitness and state-of-the-art athletic training program. Opened in 1995, the Horner Center is named in honor of Dr. John Horner, President of Hanover College from 1958-1987 and his wife, Anne.<br><br>The Horner Center contains instructional facilities for the Kinesiology and Integrative Physiology program, practice and performance areas for the College’s intercollegiate sports teams and general recreation and fitness areas. The facility features a performance gymnasium, multi-sports forum, weight room, running track, racquetball courts, classrooms, locker rooms and other related features.<br><br>Collier Arena seats 2,000 spectators for Hanover’s varsity basketball and volleyball contests. The arena can seat up to 3,000 for commencement, convocations, concerts and other community events.<br><br>Struck Gymnasium features three basketball courts and accommodates a wide range of activities such as tennis, volleyball and badminton. The space also includes indoor hitting cages for softball, baseball and golf.<br><br>Adjacent facilities include the three-lane Mitchell Running Track, three racquetball courts, a squash court and a 6,000-square-foot fitness center. The fitness center contains more than 75 pieces of weight-lifting equipment and aerobic exercise machines.<br><br><b>Regular Hours</b><br><br>Monday – Thursday: 6 a.m. – 10 p.m.<br><br>Friday: 6 a.m. – 9 p.m.<br><br>Saturday: 8 a.m. – 9 p.m.<br><br>Sunday: Noon – 9 p.m.<br><br><b>Summer Hours</b><br><br>Monday – Thursday: 6 a.m. – 7 p.m.<br><br>Friday: 6 a.m. – 6 p.m.<br><br>Saturday: 8 a.m. – 6 p.m.<br><br>Sunday: Noon – 6 p.m.");
export const arenaFeature = createFeature("Collier Arena", "Athletics", coords.arena, arenaLinks, arenaSidebar, "Collier Arena, which is located inside the Horner Health & Recreation Center, is home to the Hanover basketball and volleyball programs. The arena seats 2,000 spectators for athletics events but also can be configured for everything from concerts and speeches to dinners, meetings and graduation.<br><br>During the 2016-17 academic year, the venue not only hosted regular season events for Hanover’s athletic teams, but also the Heartland Collegiate Athletic Conference Volleyball and Men’s Basketball postseason tournaments, as well as the NCAA Division III Men’s Basketball National Tournament First and Second Rounds.<br><br>The arena also became the new home for the College’s rebranded, “Hanover Enrichment Series” in 2016-17. For non-athletic events, the facility can seat up to 3,000 people.");

// dining features
export const shoeboxFeature = createFeature("The Shoebox", "Dining", coords.shoebox, 'https://hanoverdining.catertrax.com/shopportal.asp?pageref=WeeklyMenu&intOrderID=&intCustomerID=', shoeboxSidebar, "The Shoebox is a place where you can kick back and relax with friends while enjoying various activities such as- singing karaoke, listening to DJs and bands or watching sports and your favorite TV shows. <br><br>The menu includes items such as: wraps, burgers, wings/tenders, quesadillas, salads, shakes and more! We also offer beer and wine to those who are 21 years of age and over.<br><br>ACADEMIC YEAR HOURS <br>Monday: Closed<br><br>Tuesday - Sunday: 5pm — 10pm<br><br>Meal Exchange Hours: Tuesday - Sunday: 5pm — 10pm<br>(All Plans limited to 1 swipe per Retail Meal Period)");
export const ugFeature = createFeature("The Underground", "Dining", coords.ug, 'https://hanoverdining.catertrax.com/shopportal.asp?pageref=WeeklyMenu&intOrderID=&intCustomerID=', ugSidebar, "The Underground is a grill and burrito style fast food place on campus with options varying from fried chicken sandwiches to quesadillas. It has a dark atmosphere with plenty of tables many of which have chargers making this a perfect place for a late night study snack, or when you are in a hurry and need something quick. It also has Cafe 1827 which is a starbucks.<br><br>ACADEMIC YEAR HOURS<br><br>Monday - Sunday: 11am — 11 pm<br><br>Meal Exhange Hours: Monday - Sunday 11am - 11pm" )
export const ccFeature = createFeature("Brown Campus Center", "Dining", coords.cc, 'https://hanoverdining.catertrax.com/shopportal.asp?pageref=WeeklyMenu&intOrderID=&intCustomerID=', ccSidebar, "The Brown Campus Center Open every day for Breakfast & Lunch. Open Monday through Friday for Dinner. The Brown Campus Center Dining Room is an All-You-Care-To-Eat location with all of your favorites.<br><br>ACADEMIC YEAR HOURS<br><br>Monday - Friday 7am — 8pm<br>Breakfast 7am - 11am<br>Lunch 11am - 5pm<br>Dinner 5pm - 8pm<br><br>Saturday - Sunday 8:30am — 1:30pm<br>Breakfast 8:30am - 11:00am<br>Lunch 11:00am - 1:30pm" )

// greek features
export const phiDeltaThetaFeature = createFeature("Phi Delta Theta", "Greek", coords.PhiDeltaTheta, 'https://hanover.phideltatheta.org/', phiDeltaThetaSidebar, "Phi Delta Theta (ΦΔΘ) is a fraternity founded in 1848 with a commitment to the principles of friendship, sound learning, and moral rectitude. The fraternity focuses on fostering personal growth, leadership, academic achievement, and brotherhood among its members. Phi Delta Theta aims to develop men of strong character who contribute positively to their communities and uphold high standards of integrity. The fraternity is known for its dedication to creating lasting relationships and providing a supportive environment for members' success both during college and beyond.<br><br>Phi Delta Theta is a prominent fraternity at Hanover College, focused on leadership and academic success. The fraternity provides a supportive community for its members.");
export const sigmaChiFeature = createFeature("Sigma Chi Fraternity", "Greek", coords.SigmaChi, '', sigmachiSidebar,"Sigma Chi Alpha is a local fraternity that focuses on building strong bonds of brotherhood, leadership, and personal development. It emphasizes academic achievement, community service, and fostering a supportive environment for its members. The fraternity strives to cultivate values of integrity, respect, and responsibility, while encouraging members to lead by example and contribute positively to society.")
export const lambdaChiAlphaFeature = createFeature("Lambda Chi Fraternity", "Greek", coords.Lambda, '', sigmachiSidebar, "Lambda Chi Alpha is a fraternity founded in 1909 that values friendship, leadership, scholarship, and service. It aims to create lifelong bonds of brotherhood and foster personal growth through community involvement and philanthropy. The fraternity emphasizes inclusivity, personal development, and the importance of making a positive impact on both campus and society.")
export const fijiFeature = createFeature("Phi Gamma Delta Fraternity", "Greek", coords.Fiji, '', fijiSidebar, "Fiji, or Phi Gamma Delta, is a fraternity founded in 1848 with a strong focus on friendship, knowledge, service, morality, and excellence. Its core values emphasize leadership, academic success, and the development of lifelong relationships among members. The fraternity encourages a commitment to community involvement, personal growth, and high ethical standards, aiming to create a positive impact both on campus and in the broader world.")
export const chiOmegaFeature = createFeature("Chi Omega Sorority", "Greek", coords.chiO, '', chioSidebar, "Chi Omega (ΧΩ) is a women's sorority founded in 1895 at the University of Arkansas. It is one of the largest sororities in the United States, known for its commitment to fostering friendship, personal growth, and academic excellence. Chi Omega emphasizes the importance of leadership, service, and philanthropy, and its members are encouraged to engage in community service and support charitable causes. The sorority's values are based on strong sisterhood, ethical conduct, and a lifelong commitment to personal and professional development. Chi Omega is also recognized for its dedication to supporting women and helping them achieve their full potential.")
export const adpiFeature = createFeature("Alpha Delta Pi Sorority", "Greek", coords.adpi, '', adpiSidebar, "Alpha Delta Pi (ADPi) is a sorority founded in 1851 at Wesleyan College in Macon, Georgia. It was the first secret society for women, and its core values focus on sisterhood, leadership, academic excellence, and service. ADPi is committed to fostering lifelong friendships and personal growth among its members while promoting philanthropy, particularly through its support of the Ronald McDonald House Charities. With a strong emphasis on scholarship, leadership, and community involvement, Alpha Delta Pi strives to empower women to lead with integrity and make a positive impact in their communities." )
export const phimuFeature = createFeature("Phi Mu Sorority", "Greek", coords.phimu, '', phimuSidebar, "Phi Mu is a sorority founded in 1852 at Wesleyan College in Macon, Georgia. It is one of the oldest sororities in the United States and is dedicated to promoting values of sisterhood, service, scholarship, and love. Phi Mu’s philanthropic focus is on supporting the Children’s Miracle Network Hospitals, and its members are encouraged to make a positive impact on their communities. With a rich tradition of empowering women, Phi Mu fosters personal growth, leadership, and lifelong friendships among its members. The sorority’s motto, 'Les Soeurs Fidèles' (The Faithful Sisters), reflects its commitment to enduring bonds and support.")
export const thetaFeature = createFeature("Kappa Alpha Theta Sorority", "Greek", coords.theta, '', thetaSidebar, "Kappa Alpha Theta is a sorority founded in 1870 at DePauw University in Greencastle, Indiana. It was the first Greek-letter fraternity for women and has a rich history of fostering academic excellence, leadership, and personal growth. Kappa Alpha Theta focuses on empowering women to become strong leaders and active members of their communities. Its national philanthropy is CASA (Court Appointed Special Advocates), an organization dedicated to advocating for children in the foster care system. The sorority’s motto, 'Leading Women,' reflects its commitment to developing confident, compassionate women who make a difference in the world.")
 
// residence features
export const greenwoodSuitesFeature = createFeature("Greenwood Suites", "Residence Hall", coords.greenwood, '', greenwoodSidebar, "HOUSES: 72 STUDENTS <br><br>AVERAGE ROOM SIZE: 14’1″ X 12’4″ <br><br>Students living in the Greenwood Suites are more autonomous with only upper-class students living in the complex. The individual suites in Greenwood house students in a suite of three bedrooms. Two bedrooms share a bath, while the third has its own bathroom. Two lower-level suites have roll-in showers to make them handicap-accessible. Each suite has a small efficiency kitchen with a compact refrigerator and a sink. A range is not allowed; however, the residents may bring in a microwave. All suites are air-conditioned with full laundry facilities available onsite.");
export const ogleFeature = createFeature("Ogle Center", "Residence Hall", coords.ogle, '', ogleSidebar, "HOUSES: 42 STUDENTS<br><br>AVERAGE ROOM SIZE: 11’9″ X 13’4″<br><br>The Ogle Center is a suite-style living environment. The individual suites house seven students in a suite of four bedrooms (three doubles and one single). Two bedrooms have their own bathrooms, while the third double shares a bathroom with the single room.<br><br>Each suite has a small efficiency kitchen with a compact refrigerator and a sink. A range is not allowed; however, the residents may bring in a microwave. The suite also has air-conditioning, laundry facilities and a living room with skylights.");
export const coulterFeature = createFeature("Coulter House", "Residence Hall", coords.coulter, '', coulterSidebar, "HOUSES: 38 STUDENTS<br><br>AVERAGE ROOM SIZE: 13′ X 12′<br><br>Built in 2003 and named for botanists John Merle Coulter and Stanley Moses Coulter, great-grandsons of John Finley Crowe, Hanover’s founder.<br><br>Coulter House houses approximately 38 students in a traditional style. Most rooms are doubles, but there are a few single rooms as well as one triple and one quad. There are common bathrooms for each wing, as well as common lounges and laundry facilities." );
export const croweFeature = createFeature("Crowe Hall", "Residence Hall", coords.crowe, '', croweSidebar, "HOUSES: 120 STUDENTS<br><br>AVERAGE ROOM SIZE: 13’5″ X 13’3″<br><br>Crowe Hall is one of the suite-style residence halls for first-year and upper-class residents, accommodating 120 students. There are common bathrooms for each wing, common lounges and laundry facilities." );
export const donnerFeature = createFeature("Donner Hall", "Residence Hall", coords.donner, '', donnerSidebar, "HOUSES: 120 FIRST-YEAR STUDENTS<br><br>AVERAGE ROOM SIZE: 13’1″ X 12′<br><br>First-year living featuring primarily double rooms. There are two common bathrooms per floor, one for each wing, common floor lounges and laundry facilities. This hall is co-ed by floor.<br>Donner Hall is undergoing a massive renovation in 2021 with new bathrooms, laundry room and yoga and circuit training rooms. It is also ADA-accessible via a new entrance." );
export const blytheFeature = createFeature("Blythe Hall", "Residence Hall", coords.blythe, '', blytheSidebar, "HOUSES: 40 FIRST-YEAR STUDENTS<br><br>AVERAGE ROOM SIZE: 13′ X 13′2″<br><br>Blythe features double rooms. Each floor has a common bathroom. The basement also houses a common lounge, kitchen and laundry facilities." );
export const wileyFeature = createFeature("Wiley Hall", "Residence Hall", coords.wiley, '', wileySidebar, "HOUSES: 90 STUDENTS<br><br>AVERAGE ROOM SIZE: 14’1″ X 12’4″<br><br>Wiley Hall is a traditional upper-class residence hall, accommodating 90 students in mostly single rooms. There are common bathrooms for each wing, common lounges and laundry facilities." );
export const ideFeature = createFeature("Ide Hall", "Residence Hall", coords.ide, '', ideSidebar, "HOUSES: 40 FIRST-YEAR STUDENTS<br><br>AVERAGE ROOM SIZE: 13’1″ X 13’3″<br><br>Ide Hall is a first-year residence hall with double rooms and is co-ed by floor. There are common bathrooms for each wing, common lounges and laundry facilities.<br><br>Ide just underwent a renovation in 2020 and is practically new from top to bottom, including air-conditioning in all rooms.");
export const kpFeature = createFeature("Katherine Parker Hall", "Residence Hall", coords.kp, '', kpSidebar, "HOUSES: 90 FIRST-YEAR STUDENTS<br><br>AVERAGE ROOM SIZE: 13’11” X 10’8″<br><br>Katharine Parker Hall is for first-year students, accommodating 90 students with men and women living on separate floors.<br><br>There are common bathrooms for each wing, a common lounge and laundry facilities.");
 
// Academic features
export const dugganLibraryFeature = createFeature("Duggan Library", "Library", coords.library, 'https://www.hanover.edu/library', dugganLibrarySidebar, "Duggan Library is the main library at Hanover College, offering a wide selection of books, journals, and digital resources for students and faculty.<br><br>The first floor remains open until closing time. The second and third floors close 15 minutes prior to the listed closing time.<br><br>Monday - Thursday: 7:30 a.m. - 10:00 p.m.<br>Friday: 7:30 a.m. - 5:00 p.m.<br>Saturday: noon - 5:00 p.m.<br>Sunday: 1:00 p.m. - 10:00 p.m.");
export const scienceCenterFeature = createFeature("Science Center", "Classroom", coords.scienceCenter, "", scienceCenterSidebar, "The Science Center consists of a new two-story building adjacent to an existing building, and houses classroom and laboratory space for the various science departments at the college, as well as administrative offices. The structural steel frame is clad with traditional brick architecture tying in with the historic campus. The building is topped with a copper standing steam mansard roof system complete with a widow's walk and cupola.");
export const classicHallFeature = createFeature("Classic Hall", "Classroom", coords.classic, "", classicHallSidebar, "Classic Hall was constructed on a bluff known as the Point, and College classes were moved to that location. 'Old Classic' would be Hanover's signature building for more than 90 years. However on December 19, 1941, a large fire destroyed most of Classic Hall. It has since been reconstructed and has three stories of classrooms hosting all types of courses.");
export const scienceHallFeature = createFeature("Science Hall", "Classroom", coords.scienceHall, "", scienceCenterSidebar, "Hanover College’s Science Hall is a no-nonsense, practical space that gets the job done without unnecessary frills. It provides students with the essential classrooms and labs needed for hands-on learning in biology, chemistry, and environmental science. While it may not boast state-of-the-art features or cutting-edge design, its simplicity fosters a focused academic environment where students can engage in meaningful scientific exploration. The building’s unassuming nature reflects Hanover’s dedication to providing a strong educational foundation without distractions, making it a dependable and functional part of campus life.");
export const lynnHallFeature = createFeature("Lynn Hall", "Classroom", coords.lynn, "", lynnHallSidebar, "HOUSES: 90 STUDENTS<br><br>Lynn Hall once served as the athletic area for campus.<br><br>All rooms are double rooms in various suite-style living arrangements. Each suite shares a common bathroom. The building has various common lounges, an efficiency kitchen and laundry facilities.<br><br>Lynn Hall was an underutilized gymnasium located at the center of a residential campus. The architect proposed to re-purpose Lynn Hall as an integrated live-learn community. The College accepted the plan and today the renovated building contains two large classrooms, informal study, lounges and residential suites.");
export const cfaFeature = createFeature("Lynn Center for Fine Arts", "Arts", coords.cfa, "https://www.hanover.edu/academics/programs/music/performances/", cfaSidebar, "The Lynn Center for Fine Arts at Hanover College serves as a hub for artistic expression, creativity, and performance. Home to the college’s theater, music, and visual arts programs, the facility includes a theater, recital hall, art studios, and classrooms designed to support both academic instruction and student-led productions. The center regularly hosts concerts, plays, gallery exhibitions, and other cultural events, enriching the campus community and providing students with hands-on experience in the fine arts. With its modern amenities and commitment to fostering artistic talent, the Lynn Center for Fine Arts plays a vital role in Hanover College’s dedication to a well-rounded liberal arts education.");
 
// Misc Features
export const pointFeature = createFeature("The Point", "Misc", coords.point, '', pointSidebar, "The Point at Hanover College is a breathtaking location that epitomizes the natural beauty and serene charm of the campus. Nestled on the bluffs overlooking the confluence of the Ohio River and rolling hills of Kentucky, The Point offers sweeping panoramic views that captivate students, visitors, and alumni alike. It's more than just a scenic spot; it's a place of inspiration, reflection, and connection. Whether you're watching a golden sunset, enjoying a quiet moment of study, or celebrating life’s milestones, The Point stands as a timeless symbol of Hanover's commitment to harmony between education and nature." )
export const CulberstonObservatoryFeature = createFeature("Culbertson Observatory", "Misc", coords.observatory, '', observatory, "The Hanover College Culbertson Observatory was constructed in 1992 with generous foundation and alumni contributions and houses a 16 seat classroom. The dome and original refractor type telescope were part of the original Observatory built in 1889." );


// Function to set the style of a feature dynamically based on zoom level
export const setFeatureStyle = (feature, src, zoom) => {
  const scale = 0.4 * Math.pow(2, zoom - 16); // Scale based on zoom level
  feature.setStyle(new Style({
    image: new Icon({
      src: src,
      scale: scale, // Dynamically set scale
    })
  }));
};
