lsi: false
safe: true
baseurl: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: 3D Interactive Map of Hanover College Campus
description: A map that will lead to increased web traffic for the college, distribute essential information to students, and create a connected student body.