name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy Over the App
        run: |
          mkdir -p pages
          mv dist pages/app
          
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Docs
        uses: actions/jekyll-build-pages@v1
        with:
          destination: pages/docs

      - name: Upload Static Files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with: 
          path: pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4